Mitigate quay.io instabilities by adding retries to commands using registry
STONEBLD-3488

Signed-off-by: Robert Cerven <rcerven@redhat.com>

diff --git a/task/push-dockerfile/0.1/push-dockerfile.yaml b/task/push-dockerfile/0.1/push-dockerfile.yaml
--- a/task/push-dockerfile/0.1/push-dockerfile.yaml
+++ b/task/push-dockerfile/0.1/push-dockerfile.yaml
@@ -108,12 +108,17 @@ spec:
       dockerfile_for_upload_path=/tmp/Dockerfile
       cp "$dockerfile_path" "$dockerfile_for_upload_path"
       cd "$(dirname $dockerfile_for_upload_path)"
-      retry oras push --no-tty \
+      echo "Pushing Dockerfile to registry"
+      if ! retry oras push --no-tty \
         --format json \
         --registry-config "$auth_json" \
         --artifact-type "$ARTIFACT_TYPE" \
         "$dockerfile_image" "$(basename $dockerfile_for_upload_path)" \
         | yq '.reference' | tr -d '\r\n' >"$IMAGE_REF_RESULT"
+      then
+        echo "Failed to push Dockerfile to registry"
+        exit 1
+      fi
 
   workspaces:
   - name: workspace
diff --git a/task/sast-shell-check/0.1/sast-shell-check.yaml b/task/sast-shell-check/0.1/sast-shell-check.yaml
--- a/task/sast-shell-check/0.1/sast-shell-check.yaml
+++ b/task/sast-shell-check/0.1/sast-shell-check.yaml
@@ -274,7 +274,11 @@ spec:
             echo "Selecting auth"
             select-oci-auth "$IMAGE_URL" > "$HOME/auth.json"
             echo "Attaching to ${IMAGE_URL}"
-            retry oras attach --no-tty --registry-config "$HOME/auth.json" --artifact-type "${MEDIA_TYPE}" "${IMAGE_URL}@${IMAGE_DIGEST}" "${UPLOAD_FILE}:${MEDIA_TYPE}"
+            if ! retry oras attach --no-tty --registry-config "$HOME/auth.json" --artifact-type "${MEDIA_TYPE}" "${IMAGE_URL}@${IMAGE_DIGEST}" "${UPLOAD_FILE}:${MEDIA_TYPE}"
+            then
+              echo "Failed to attach ${UPLOAD_FILE} to ${IMAGE_URL}"
+              exit 1
+            fi
         done
   workspaces:
   - name: workspace
