Implement conditional releasing for tekton bundle builder pipeline
Check the previous version of a task using git. Compare the actual
version with previous version and use "release-only-if-version-bumped"
pipeline parameter to evaluate the final result.

Signed-off-by: Michal Šoltis <msoltis@redhat.com>

diff --git a/task/tkn-bundle-oci-ta/0.2/tkn-bundle-oci-ta.yaml b/task/tkn-bundle-oci-ta/0.2/tkn-bundle-oci-ta.yaml
--- a/task/tkn-bundle-oci-ta/0.2/tkn-bundle-oci-ta.yaml
+++ b/task/tkn-bundle-oci-ta/0.2/tkn-bundle-oci-ta.yaml
@@ -277,9 +277,30 @@ spec:
           yq ".metadata.labels.\"${LABEL_ACTUAL_TASK_VERSION}\"" "$task_file" | sed '/null/d' | tr -d '[:space:]'
         }
 
+        get_previous_task_version() {
+          local -r task_file=$1
+          local -r task_relpath="${task_file#*/"${SOURCE_CODE_DIR}"/}"
+
+          local previous_yaml
+          if ! previous_yaml=$(git -C "${SOURCE_CODE_DIR}" show "HEAD^:${task_relpath}"); then
+            echo "Could not get previous task version" >&2
+            return 0
+          fi
+          yq ".metadata.labels.\"${LABEL_ACTUAL_TASK_VERSION}\"" <<<"${previous_yaml}" | sed '/null/d' | tr -d '[:space:]'
+        }
+
         # task_dir is where the task definition reside
         # this task run for only one task file, so extracting it from the first element is enough
         task_dir=$(echo "${FILES[0]}" | awk -F'/' '{NF--; print $0}' OFS='/')
+
+        original_task_file=""
+        for f in "${FILES[@]}"; do
+          if [[ -n "$(get_actual_task_version "$f")" ]]; then
+            original_task_file="$f"
+            break
+          fi
+        done
+        : "${original_task_file:=${FILES[0]}}"
 
         # If task is kustomized, generate it and replace the FILES value with the value of the generated task
         # All other files will be ignored.
@@ -291,10 +312,26 @@ spec:
         fi
 
         actual_task_version=$(get_actual_task_version "${FILES[0]}")
+        echo "Found actual task version: $actual_task_version"
 
         if [[ "$(yq .kind "${FILES[0]}")" == Task && -z "$actual_task_version" ]]; then
           printf "Label %s is not set in task file %s\n" "$LABEL_ACTUAL_TASK_VERSION" "${FILES[0]}" >&2
           exit 1
+        fi
+
+        SHOULD_RELEASE="false"
+        if [[ "$RELEASE_ONLY_IF_VERSION_BUMPED" == "true" ]]; then
+          current_task_version=$(get_actual_task_version "${original_task_file}")
+          previous_task_version=$(get_previous_task_version "${original_task_file}")
+
+          echo "Found current task version: $current_task_version"
+          echo "Found previous task version: $previous_task_version"
+
+          if [[ "$current_task_version" != "$previous_task_version" ]]; then
+            SHOULD_RELEASE="true"
+          fi
+        else
+          SHOULD_RELEASE="true"
         fi
 
         # Push migration to registry if there is
@@ -399,7 +436,7 @@ spec:
         echo -n "$IMAGE" >"$(results.IMAGE_URL.path)"
         echo -n "${digest}" >"$(results.IMAGE_DIGEST.path)"
         echo -n "${IMAGE_REF}" >"$(results.IMAGE_REF.path)"
-        echo -n "true" >"$(results.SHOULD_RELEASE.path)"
+        echo -n "${SHOULD_RELEASE}" >"$(results.SHOULD_RELEASE.path)"
 
         # cleanup task file
         # shellcheck disable=SC2153
