rpm-ostree: use prefetched RPMs, add hermetic option (#928)
* prefetch-dependencies: expose dev-package-managers

STONEBLD-2280
STONEBLD-2281

The experimental RPM support that's being added to cachi2 will stay
gated behind the --dev-package-managers flag. Give users a way to enable
dev package managers.

Document the option as discouraged.

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

* rpm-ostree: use prefetched RPMs when available

STONEBLD-2281

When the prefetch-dependencies task prefetches RPMs, make the
rpm-ostree task use them. Do this by removing all the original repo
files from the source directory and replacing them with the generated
cachi2.repo.

---

Note that the rpm-ostree task determines whether there are prefetched
RPMs by checking the existence of the platform-specific RPMs directory.
This means that if RPMs are prefetched for platform A but not for
platform B, the build for platform B will still work (and download the
RPMs at build time).

One may argue that this is undesirable, as it can lead to a situation
where one platform prefetches RPMs and another one does not. But this is
best addressed by enabling the 'hermetic' option to cut off network
access altogether (to be added in a follow-up commit).

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

* rpm-ostree: make podman line more human-friendly

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

* rpm-ostree: add hermetic option

STONEBLD-2281

With HERMETIC=true, the rpm-ostree build will have its network access
disabled.

This is done by setting --network=none for the podman container executed
on the remote VM (which runs the rpm-ostree command). Note that
rpm-ostree has an --offline option, but it doesn't do anything useful
for hermetic builds. Just prints a warning when RPMs have to be
downloaded.

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

---------

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

diff --git a/task/rpm-ostree/0.1/rpm-ostree.yaml b/task/rpm-ostree/0.1/rpm-ostree.yaml
--- a/task/rpm-ostree/0.1/rpm-ostree.yaml
+++ b/task/rpm-ostree/0.1/rpm-ostree.yaml
@@ -52,6 +52,10 @@ spec:
     name: CONFIG_FILE
     type: string
     default: ""
+  - default: "false"
+    description: Determines if build will be executed without network access.
+    name: HERMETIC
+    type: string
   results:
   - description: Digest of the image just built
     name: IMAGE_DIGEST
@@ -77,6 +81,8 @@ spec:
       value: $(params.BUILDER_IMAGE)
     - name: CONFIG_FILE
       value: $(params.CONFIG_FILE)
+    - name: HERMETIC
+      value: $(params.HERMETIC)
     computeResources: {}
   steps:
   - env:
@@ -126,12 +132,54 @@ spec:
       else
         CONFIG_FILE_ARG="  --image-config=source/$CONFIG_FILE "
       fi
-      rpm-ostree compose image --initialize --format oci $CONFIG_FILE_ARG "source/$IMAGE_FILE" rhtap-final-image
 
+      prefetched_rpms_for_my_arch="./cachi2/output/deps/rpm/$(uname -m)"
+      if [ -d "$prefetched_rpms_for_my_arch" ]; then
+        # move all repo files out of the source repository to avoid conflicts with the cachi2.repo
+        mkdir /tmp/original-repos
+        find ./source -maxdepth 1 -name '*.repo' -exec mv {} /tmp/original-repos \;
+
+        # copy the platform-specific cachi2.repo into the source repository
+        cp "$prefetched_rpms_for_my_arch/repos.d/cachi2.repo" ./source
+
+        # set up cleanup handler
+        trap 'rm ./source/cachi2.repo; cp -r /tmp/original-repos/. ./source' EXIT
+
+        # link the cachi2 output dir to the expected location
+        #   (the prefetch task expects the output to be at /cachi2/output during the build)
+        mkdir /cachi2
+        ln -s "$(realpath ./cachi2/output)" /cachi2/output
+      fi
+
+      rpm-ostree compose image --initialize --format oci $CONFIG_FILE_ARG "source/$IMAGE_FILE" rhtap-final-image
       REMOTESSHEOF
+
+      if [ "$HERMETIC" = "true" ]; then
+        network_opt="--network=none"
+      else
+        network_opt=""
+      fi
+
       chmod +x scripts/script-build.sh
       rsync -ra scripts "$SSH_HOST:$BUILD_DIR"
-      ssh $SSH_ARGS "$SSH_HOST" podman run --mount type=bind,source=$BUILD_DIR/tmp,target=/var/tmp,relabel=shared --privileged -e CONTEXT="$CONTEXT" -e IMAGE_FILE="$IMAGE_FILE" -e CONFIG_FILE="$CONFIG_FILE" -e IMAGE="$IMAGE" -e IMAGE_EXPIRES_AFTER="$IMAGE_EXPIRES_AFTER" -e COMMIT_SHA="$COMMIT_SHA"  --rm  -v "$BUILD_DIR/workspaces/source:$(workspaces.source.path):Z"  -v $BUILD_DIR/scripts:/script:Z --user=0 --entrypoint bash "$BUILDER_IMAGE" /script/script-build.sh
+      ssh $SSH_ARGS "$SSH_HOST" \
+        podman run \
+          $network_opt \
+          --mount type=bind,source=$BUILD_DIR/tmp,target=/var/tmp,relabel=shared \
+          --privileged \
+          -e CONTEXT="$CONTEXT" \
+          -e IMAGE_FILE="$IMAGE_FILE" \
+          -e CONFIG_FILE="$CONFIG_FILE" \
+          -e IMAGE="$IMAGE" \
+          -e IMAGE_EXPIRES_AFTER="$IMAGE_EXPIRES_AFTER" \
+          -e COMMIT_SHA="$COMMIT_SHA" \
+          --rm \
+          -v "$BUILD_DIR/workspaces/source:$(workspaces.source.path):Z" \
+          -v $BUILD_DIR/scripts:/script:Z \
+          --user=0 \
+          --entrypoint bash \
+          "$BUILDER_IMAGE" \
+          /script/script-build.sh
       rsync -ra "$SSH_HOST:$BUILD_DIR/workspaces/source/" "$(workspaces.source.path)/"
       cp -r rhtap-final-image /var/lib/containers/rhtap-final-image
       buildah pull oci:rhtap-final-image
