rpm-ostree: use prefetched RPMs when available
STONEBLD-2281

When the prefetch-dependencies task prefetches RPMs, make the
rpm-ostree task use them. Do this by removing all the original repo
files from the source directory and replacing them with the generated
cachi2.repo.

---

Note that the rpm-ostree task determines whether there are prefetched
RPMs by checking the existence of the platform-specific RPMs directory.
This means that if RPMs are prefetched for platform A but not for
platform B, the build for platform B will still work (and download the
RPMs at build time).

One may argue that this is undesirable, as it can lead to a situation
where one platform prefetches RPMs and another one does not. But this is
best addressed by enabling the 'hermetic' option to cut off network
access altogether (to be added in a follow-up commit).

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

diff --git a/task/rpm-ostree/0.1/rpm-ostree.yaml b/task/rpm-ostree/0.1/rpm-ostree.yaml
--- a/task/rpm-ostree/0.1/rpm-ostree.yaml
+++ b/task/rpm-ostree/0.1/rpm-ostree.yaml
@@ -126,6 +126,25 @@ spec:
       else
         CONFIG_FILE_ARG="  --image-config=source/$CONFIG_FILE "
       fi
+
+      prefetched_rpms_for_my_arch="./cachi2/output/deps/rpm/$(uname -m)"
+      if [ -d "$prefetched_rpms_for_my_arch" ]; then
+        # move all repo files out of the source repository to avoid conflicts with the cachi2.repo
+        mkdir /tmp/original-repos
+        find ./source -maxdepth 1 -name '*.repo' -exec mv {} /tmp/original-repos \;
+
+        # copy the platform-specific cachi2.repo into the source repository
+        cp "$prefetched_rpms_for_my_arch/repos.d/cachi2.repo" ./source
+
+        # set up cleanup handler
+        trap 'rm ./source/cachi2.repo; cp -r /tmp/original-repos/. ./source' EXIT
+
+        # link the cachi2 output dir to the expected location
+        #   (the prefetch task expects the output to be at /cachi2/output during the build)
+        mkdir /cachi2
+        ln -s "$(realpath ./cachi2/output)" /cachi2/output
+      fi
+
       rpm-ostree compose image --initialize --format oci $CONFIG_FILE_ARG "source/$IMAGE_FILE" rhtap-final-image
 
       REMOTESSHEOF
