Mitigate quay.io instabilities by adding retries to commands using registry
STONEBLD-3488

Signed-off-by: Robert Cerven <rcerven@redhat.com>

diff --git a/task/clamav-scan/0.2/clamav-scan.yaml b/task/clamav-scan/0.2/clamav-scan.yaml
--- a/task/clamav-scan/0.2/clamav-scan.yaml
+++ b/task/clamav-scan/0.2/clamav-scan.yaml
@@ -307,7 +307,11 @@ spec:
         echo "Selecting auth"
         select-oci-auth $IMAGE_URL > $HOME/auth.json
         echo "Attaching to ${IMAGE_URL}"
-         retry oras attach --no-tty --registry-config "$HOME/auth.json" --artifact-type application/vnd.clamav "${IMAGE_URL}@${IMAGE_DIGEST}" "${args[@]}"
+        if ! retry oras attach --no-tty --registry-config "$HOME/auth.json" --artifact-type application/vnd.clamav "${IMAGE_URL}@${IMAGE_DIGEST}" "${args[@]}"
+        then
+          echo "Failed to attach to ${IMAGE_URL}"
+          exit 1
+        fi
       volumeMounts:
         - mountPath: /work
           name: work
diff --git a/task/sast-coverity-check/0.3/patch.yaml b/task/sast-coverity-check/0.3/patch.yaml
--- a/task/sast-coverity-check/0.3/patch.yaml
+++ b/task/sast-coverity-check/0.3/patch.yaml
@@ -512,13 +512,22 @@
         set -x
         UPLOAD_FILE="$1"
         MEDIA_TYPE="$2"
-        retry oras attach --no-tty --registry-config "${HOME}/auth.json" --artifact-type "${MEDIA_TYPE}" "${IMAGE_URL}@${IMAGE_DIGEST}" "${UPLOAD_FILE}:${MEDIA_TYPE}"
+        oras attach --no-tty --registry-config "${HOME}/auth.json" --artifact-type "${MEDIA_TYPE}" "${IMAGE_URL}@${IMAGE_DIGEST}" "${UPLOAD_FILE}:${MEDIA_TYPE}"
       )
 
       echo "Attaching scan results to ${IMAGE_URL}"
-      upload_file "coverity-results.sarif" "application/sarif+json"
+      if ! retry upload_file "coverity-results.sarif" "application/sarif+json"
+      then
+        echo "Failed to attach scan results to ${IMAGE_URL}"
+        exit 1
+      fi
 
       # upload excluded-findings.json if enabled
       if [ -f "excluded-findings.json" ]; then
-        upload_file "excluded-findings.json" "application/json"
+        echo "Attaching excluded findings to ${IMAGE_URL}"
+        if ! retry upload_file "excluded-findings.json" "application/json"
+        then
+          echo "Failed to attach excluded findings to ${IMAGE_URL}"
+          exit 1
+        fi
       fi
diff --git a/task/source-build-oci-ta/0.2/source-build-oci-ta.yaml b/task/source-build-oci-ta/0.2/source-build-oci-ta.yaml
--- a/task/source-build-oci-ta/0.2/source-build-oci-ta.yaml
+++ b/task/source-build-oci-ta/0.2/source-build-oci-ta.yaml
@@ -82,7 +82,11 @@ spec:
 
         echo "BASE_IMAGES param is empty, inspecting the SBOM instead"
 
-        raw_inspect=$(skopeo inspect --raw "docker://$BINARY_IMAGE")
+        skopeo_retries=3
+        if ! raw_inspect=$(retry skopeo inspect --raw --retry-times "$skopeo_retries" "docker://$BINARY_IMAGE"); then
+          echo "Failed to inspect ${BINARY_IMAGE}"
+          exit 1
+        fi
         if manifest_digest=$(jq -e -r '.manifests[0].digest' <<<"$raw_inspect"); then
           # The BINARY_IMAGE is an image index, each manifest in the list has its own SBOM.
           # We're gonna assume the base images are the same or similar enough in all the SBOMs.
