Mitigate quay.io instabilities by adding retries to commands using registry
STONEBLD-3488

Signed-off-by: Robert Cerven <rcerven@redhat.com>

diff --git a/task/buildah/0.4/buildah.yaml b/task/buildah/0.4/buildah.yaml
--- a/task/buildah/0.4/buildah.yaml
+++ b/task/buildah/0.4/buildah.yaml
@@ -598,6 +598,27 @@ spec:
       #!/bin/bash
       set -e
 
+      retry() {
+        local status
+        local interval=1
+        local retry=0
+        local -r factor=2
+        local -r max_retries=10
+        while true; do
+          "$@" && break
+          status=$?
+          ((retry += 1))
+          if [ $retry -gt $max_retries ]; then
+            echo "warning: Command failed and reached max retries" 1>&2
+            return $status
+          fi
+          echo "warning: Command failed and will retry" 1>&2
+
+          ((interval = interval * factor))
+          sleep "$interval"
+        done
+      }
+
       echo "[$(date --utc -Ins)] Update CA trust"
 
       ca_bundle=/mnt/trusted-ca/ca-bundle.crt
@@ -619,17 +640,18 @@ spec:
 
       echo "[$(date --utc -Ins)] Push image with unique tag"
 
-      retries=5
+      buildah_retries=5
+
       # Push to a unique tag based on the TaskRun name to avoid race conditions
       echo "Pushing to ${IMAGE%:*}:${TASKRUN_NAME}"
-      if ! buildah push \
+      if ! retry buildah push \
         --format="$push_format" \
-        --retry "$retries" \
+        --retry "$buildah_retries" \
         --tls-verify="$TLSVERIFY" \
         "$IMAGE" \
-        "docker://${IMAGE%:*}:$(context.taskRun.name)";
+        "docker://${IMAGE%:*}:$(context.taskRun.name)"
       then
-        echo "Failed to push sbom image to ${IMAGE%:*}:$(context.taskRun.name) after ${retries} tries"
+        echo "Failed to push sbom image to ${IMAGE%:*}:$(context.taskRun.name)"
         exit 1
       fi
 
@@ -637,14 +659,14 @@ spec:
 
       # Push to a tag based on the git revision
       echo "Pushing to ${IMAGE}"
-      if ! buildah push \
+      if ! retry buildah push \
         --format="$push_format" \
-        --retry "$retries" \
+        --retry "$buildah_retries" \
         --tls-verify="$TLSVERIFY" \
         --digestfile "$(workspaces.source.path)/image-digest" "$IMAGE" \
-        "docker://$IMAGE";
+        "docker://$IMAGE"
       then
-        echo "Failed to push sbom image to $IMAGE after ${retries} tries"
+        echo "Failed to push sbom image to $IMAGE"
         exit 1
       fi
 
@@ -799,6 +821,27 @@ spec:
     script: |
       #!/bin/bash
 
+      retry() {
+        local status
+        local interval=1
+        local retry=0
+        local -r factor=2
+        local -r max_retries=10
+        while true; do
+          "$@" && break
+          status=$?
+          ((retry += 1))
+          if [ $retry -gt $max_retries ]; then
+            echo "warning: Command failed and reached max retries" 1>&2
+            return $status
+          fi
+          echo "warning: Command failed and will retry" 1>&2
+
+          ((interval = interval * factor))
+          sleep "$interval"
+        done
+      }
+
       echo "[$(date --utc -Ins)] Upload SBOM"
 
       if [ "${SKIP_SBOM_GENERATION}" = "true" ]; then
@@ -815,7 +858,14 @@ spec:
 
       # Pre-select the correct credentials to work around cosign not supporting the containers-auth.json spec
       mkdir -p /tmp/auth && select-oci-auth "$(cat "$(results.IMAGE_REF.path)")" > /tmp/auth/config.json
-      DOCKER_CONFIG=/tmp/auth cosign attach sbom --sbom sbom.json --type "$SBOM_TYPE" "$(cat "$(results.IMAGE_REF.path)")"
+      # shellcheck disable=SC2034  # Variable is used by cosign indirectly
+      DOCKER_CONFIG=/tmp/auth
+      echo "Pushing sbom to registry"
+      if ! retry cosign attach sbom --sbom sbom.json --type "$SBOM_TYPE" "$(cat "$(results.IMAGE_REF.path)")"
+      then
+          echo "Failed to push sbom to registry"
+          exit 1
+      fi
 
       # Remove tag from IMAGE while allowing registry to contain a port number.
       sbom_repo="${IMAGE%:*}"
