Mitigate quay.io instabilities by adding retries to commands using registry
STONEBLD-3488

Signed-off-by: Robert Cerven <rcerven@redhat.com>

diff --git a/archived-tasks/sast-coverity-check/0.2/sast-coverity-check.yaml b/archived-tasks/sast-coverity-check/0.2/sast-coverity-check.yaml
--- a/archived-tasks/sast-coverity-check/0.2/sast-coverity-check.yaml
+++ b/archived-tasks/sast-coverity-check/0.2/sast-coverity-check.yaml
@@ -536,9 +536,14 @@ spec:
       if [ "${HERMETIC}" == "true" ]; then
         BUILDAH_ARGS+=("--pull=never")
         UNSHARE_ARGS+=("--net")
+        buildah_retries=3
 
         for image in $BASE_IMAGES; do
-          unshare -Ufp --keep-caps -r --map-users 1,1,65536 --map-groups 1,1,65536 --mount -- buildah pull "$image"
+          if ! retry unshare -Ufp --keep-caps -r --map-users 1,1,65536 --map-groups 1,1,65536 --mount -- buildah pull --retry "$buildah_retries" "$image"
+          then
+            echo "Failed to pull base image ${image}"
+            exit 1
+          fi
         done
         echo "Build will be executed with network isolation"
       fi
diff --git a/task/build-helm-chart-oci-ta/0.1/build-helm-chart-oci-ta.yaml b/task/build-helm-chart-oci-ta/0.1/build-helm-chart-oci-ta.yaml
--- a/task/build-helm-chart-oci-ta/0.1/build-helm-chart-oci-ta.yaml
+++ b/task/build-helm-chart-oci-ta/0.1/build-helm-chart-oci-ta.yaml
@@ -144,10 +144,13 @@ spec:
 
         dest="oci://${REPO%/*}"
 
-        output=$(
-          helm push "$chart_name"-"$chart_version".tgz "$dest" \
-            --registry-config ./scoped_authfile.json 2>&1
-        )
+        echo "Pushing image to registry"
+        if ! output="$(retry helm push "$chart_name"-"$chart_version".tgz "$dest" \
+          --registry-config ./scoped_authfile.json 2>&1)"; then
+          echo "Failed to push image to registry"
+          exit 1
+        fi
+
         pushed=$(echo "$output" | grep "Pushed" | awk '{print $2}')
         digest=$(echo "$output" | grep "Digest" | awk '{print $2}')
 
diff --git a/task/build-paketo-builder-oci-ta/0.2/build-paketo-builder-oci-ta.yaml b/task/build-paketo-builder-oci-ta/0.2/build-paketo-builder-oci-ta.yaml
--- a/task/build-paketo-builder-oci-ta/0.2/build-paketo-builder-oci-ta.yaml
+++ b/task/build-paketo-builder-oci-ta/0.2/build-paketo-builder-oci-ta.yaml
@@ -202,6 +202,15 @@ spec:
         cat >scripts/script-build.sh <<'REMOTESSHEOF'
         #!/bin/sh
 
+        REMOTESSHEOF
+
+        # import retry function
+        # remove line with bash
+        # shellcheck disable=SC2002
+        cat /usr/bin/retry | sed 1d >> scripts/script-build.sh
+
+        cat >>scripts/script-build.sh <<'REMOTESSHEOF'
+
         cd /var/workdir
 
         echo "Build the builder image using pack"
@@ -237,15 +246,24 @@ spec:
 
         if [ "${HERMETIC}" == "true" ]; then
           UNSHARE_ARGS+=("--net")
+          buildah_retries=3
 
           for image in ${BASE_IMAGES}; do
             echo "Pull the base image: $image using unshare"
-            unshare -Ufp --keep-caps -r --map-users 1,1,65536 --map-groups 1,1,65536 -- buildah pull $image
+            if ! retry unshare -Ufp --keep-caps -r --map-users 1,1,65536 --map-groups 1,1,65536 -- buildah pull --retry "$buildah_retries" $image
+            then
+              echo "Failed to pull base image ${image}"
+              exit 1
+            fi
           done
 
           for image in ${BUILDPACKS_IMAGES}; do
             echo "Pull the buildpacks image: $image using unshare"
-            unshare -Ufp --keep-caps -r --map-users 1,1,65536 --map-groups 1,1,65536 -- buildah pull $image
+            if ! retry unshare -Ufp --keep-caps -r --map-users 1,1,65536 --map-groups 1,1,65536 -- buildah pull --retry "$buildah_retries" $image
+            then
+              echo "Failed to pull buildpack image ${image}"
+              exit 1
+            fi
           done
 
           echo "Fetch lifecycle and patch the ${PACK_BUILDER_FILE} file ..."
@@ -449,32 +467,31 @@ spec:
 
         buildah --storage-driver "$STORAGE_DRIVER" commit "${BUILDAH_ARGS[@]}" "$container" "$IMAGE"
 
-        echo "Pushing to ${IMAGE%:*}:${TASKRUN_NAME}"
+        buildah_retries=3
 
-        retries=5
-        if ! buildah push \
-          --retry "$retries" \
+        echo "Pushing to ${IMAGE%:*}:${TASKRUN_NAME}"
+        if ! retry buildah push \
+          --retry "$buildah_retries" \
           --storage-driver "$STORAGE_DRIVER" \
           --tls-verify="$TLSVERIFY" \
           "$IMAGE" \
-          "docker://${IMAGE%:*}:${TASKRUN_NAME}"; then
-          echo "Failed to push sbom image to ${IMAGE%:*}:${TASKRUN_NAME} after ${retries} tries"
+          "docker://${IMAGE%:*}:${TASKRUN_NAME}"
+        then
+          echo "Failed to push image ${IMAGE%:*}:${TASKRUN_NAME} to registry"
           exit 1
         fi
 
-
         echo "Pushing to ${IMAGE}"
-
-        if ! buildah push \
-          --retry "$retries" \
+        if ! retry buildah push \
+          --retry "$buildah_retries" \
           --storage-driver "$STORAGE_DRIVER" \
           --tls-verify="$TLSVERIFY" \
           --digestfile "/var/workdir/image-digest" "$IMAGE" \
-          "docker://$IMAGE"; then
-          echo "Failed to push sbom image to $IMAGE after ${retries} tries"
+          "docker://$IMAGE"
+        then
+          echo "Failed to push image $IMAGE to registry"
           exit 1
         fi
-
 
         echo "Save the different results"
 
@@ -528,7 +545,12 @@ spec:
           update-ca-trust
         fi
 
-        cosign attach sbom --sbom sbom.json --type "$SBOM_TYPE" "$(cat "$(results.IMAGE_REF.path)")"
+        echo "Pushing sbom to registry"
+        if ! retry cosign attach sbom --sbom sbom.json --type "$SBOM_TYPE" "$(cat "$(results.IMAGE_REF.path)")"
+        then
+            echo "Failed to push sbom to registry"
+            exit 1
+        fi
       volumeMounts:
         - mountPath: /mnt/trusted-ca
           name: trusted-ca
diff --git a/task/tkn-bundle-oci-ta/0.2/tkn-bundle-oci-ta.yaml b/task/tkn-bundle-oci-ta/0.2/tkn-bundle-oci-ta.yaml
--- a/task/tkn-bundle-oci-ta/0.2/tkn-bundle-oci-ta.yaml
+++ b/task/tkn-bundle-oci-ta/0.2/tkn-bundle-oci-ta.yaml
@@ -162,23 +162,6 @@ spec:
           exit 1
         exec 3>&1
 
-        retry() {
-          local status
-          local retry=0
-          local -r interval=${RETRY_INTERVAL:-5}
-          local -r max_retries=5
-          while true; do
-            "$@" && break
-            status=$?
-            ((retry += 1))
-            if [ $retry -gt $max_retries ]; then
-              return $status
-            fi
-            echo "info: Waiting for a while, then retry ..." 1>&2
-            sleep "$interval"
-          done
-        }
-
         function escape_tkn_bundle_arg() {
           # the arguments to `tkn bundle --annotate` need to be escaped in a curious way
           # see https://github.com/tektoncd/cli/issues/2402 for details
@@ -251,10 +234,14 @@ spec:
           echo "    - $annotation"
         done
 
+        echo "Pushing bundle ${IMAGE} to registry"
         # shellcheck disable=SC2046
-        OUT="$(retry tkn bundle push "${ANNOTATION_FLAGS[@]}" "$IMAGE" \
+        if ! OUT="$(retry tkn bundle push "${ANNOTATION_FLAGS[@]}" "$IMAGE" \
           $(printf ' -f %s' "${FILES[@]}") |
-          tee /proc/self/fd/3)"
+          tee /proc/self/fd/3)"; then
+          echo "Failed to push bundle ${IMAGE} to registry"
+          exit 1
+        fi
         echo -n "$IMAGE" >"$(results.IMAGE_URL.path)"
         digest="${OUT#*Pushed Tekton Bundle to *@}"
         echo -n "${digest}" >"$(results.IMAGE_DIGEST.path)"
