HACBS-1821-support dual catalog format

diff --git a/task/fbc-related-image-check/0.1/fbc-related-image-check.yaml b/task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
--- a/task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
+++ b/task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
@@ -30,12 +30,19 @@ spec:
         FAILEDIMAGES=""
         catalog="$(find $(workspaces.workspace.path)/hacbs/fbc-validation/ -name catalog.yaml)"
 
+        # OPM generates catalog file in a way that yaml file could contain stream of JSON objects
+        # thats why we need jq in for this situation, because yq can't parse this file
+        # however there is also posibility that catalog.yaml has yaml data in it
+
         relImgs="$(yq -r '.relatedImages[]?.image' $catalog)"
         if [ $? -ne 0 ]; then
-          echo "Could not get related images, make sure catalog.yaml exists in FBC fragment image and has valid yaml format."
-          HACBS_TEST_OUTPUT="$(make_result_json -r FAILURE -f 1)"
-          echo "${HACBS_TEST_OUTPUT}" | tee "$(results.HACBS_TEST_OUTPUT.path)"
+          relImgs="$(jq -r '.relatedImages[]?.image' $catalog)"
+          if [ $? -ne 0 ]; then
+            echo "Could not get related images, make sure catalog.yaml exists in FBC fragment image and has valid yaml format."
+            HACBS_TEST_OUTPUT="$(make_result_json -r FAILURE -f 1)"
+            echo "${HACBS_TEST_OUTPUT}" | tee "$(results.HACBS_TEST_OUTPUT.path)"
           exit 0
+          fi
         fi
 
         echo -e "These are related images:\n$relImgs"
