feat(STONEINTG-1232): split attach_migration_file function
* split long function attach_migration_file since generate-ta-task.sh
  can't handle it well

Signed-off-by: Hongwei Liu <hongliu@redhat.com>

diff --git a/task/tkn-bundle/0.2/tkn-bundle.yaml b/task/tkn-bundle/0.2/tkn-bundle.yaml
--- a/task/tkn-bundle/0.2/tkn-bundle.yaml
+++ b/task/tkn-bundle/0.2/tkn-bundle.yaml
@@ -143,6 +143,8 @@ spec:
       declare -r ARTIFACT_TYPE_TEXT_XSHELLSCRIPT="text/x-shellscript"
       # The annotation value points to the task bundle which has a migration that's most recent to the task with the annotation
       declare -r ANNOTATION_PREVIOUS_MIGRATION_BUNDLE="dev.konflux-ci.task.previous-migration-bundle"
+      # The annotation means to check if the manifest is from task bundle
+      declare -r ANNOTATION_TASK_BUNDLE_DESCRIPTION="org.opencontainers.image.description"
 
       mapfile -t FILES <"${TASK_FILE}"
       [[ ${#FILES[@]} -eq 0 ]] &&
@@ -188,113 +190,127 @@ spec:
           yq '.metadata.labels."app.kubernetes.io/version"' "$task_file" | sed '/null/d' | tr -d '[:space:]'
       }
 
-      # Attach migration file to given task bundle.
-      # Arguments: task_dir, concrete_task_version, task_bundle
-      attach_migration_file() {
-          local -r task_dir=$1
-          local -r concrete_task_version=$2
-          local -r task_bundle=$3
-          local -r migration_file=$4
+      # check if migration file exists in given task bundle and task_version.
+      # Arguments: task_bundle, task_version, migration_file
+      bundle_has_migration() {
+        local -r task_bundle=$1
+        local -r task_version=$2
+        local -r migration_file=$3
 
-          # Check if task bundle has an attached migration file.
-          local filename
-          local found=
-          local artifact_refs
+        # Check if task bundle has an attached migration file.
+        local filename
+        local found=
+        local artifact_refs
 
-          # List attached artifacts, that have specific artifact type and annotation.
-          # Then, find out the migration artifact.
-          #
-          # Minimum version oras 1.2.0 is required for option --format
-          artifact_refs=$(
-              retry oras discover "$task_bundle" --artifact-type "$ARTIFACT_TYPE_TEXT_XSHELLSCRIPT" --format json | \
-              jq -r "
-                  .manifests[]
-                  | select(.annotations.\"${ANNOTATION_IS_MIGRATION}\" == \"true\")
-                  | .reference"
-          )
-          while read -r artifact_ref; do
-              if [ -z "$artifact_ref" ]; then
-                  continue
-              fi
-              filename=$(
-                  retry oras pull --format json "$artifact_ref" | jq -r "
-                      .files[]
-                      | select(.annotations.\"org.opencontainers.image.title\" == \"${concrete_task_version}.sh\")
-                      | .annotations.\"org.opencontainers.image.title\"
-                      "
-              )
-
-              if [ -n "$filename" ]; then
-                  if diff "$filename" "$migration_file" >/dev/null; then
-                      found=true
-                      break
-                  else
-                      echo "error: task bundle $task_bundle has migration artifact $artifact_ref, but the migration content is different: $filename" 1>&2
-                      exit 1
-                  fi
-              fi
-          done <<<"$artifact_refs"
-
-          if [ -n "$found" ]; then
-              return 0
+        # List attached artifacts, that have specific artifact type and annotation.
+        # Then, find out the migration artifact.
+        #
+        # Minimum version oras 1.2.0 is required for option --format
+        artifact_refs=$(
+          oras discover "$task_bundle" --artifact-type "$ARTIFACT_TYPE_TEXT_XSHELLSCRIPT" --format json | \
+          jq -r "
+            .manifests[]
+            | select(.annotations.\"${ANNOTATION_IS_MIGRATION}\" == \"true\")
+            | .reference"
+        )
+        while read -r artifact_ref; do
+          if [ -z "$artifact_ref" ]; then
+              continue
           fi
-
-          (
-              cd "${migration_file%/*}"
-              retry oras attach \
-                  --registry-config "$AUTH_JSON" \
-                  --artifact-type "$ARTIFACT_TYPE_TEXT_XSHELLSCRIPT" \
-                  --annotation "${ANNOTATION_IS_MIGRATION}=true" \
-                  "$task_bundle" "${migration_file##*/}"
+          filename=$(
+            retry oras pull --format json "$artifact_ref" | jq -r "
+              .files[]
+              | select(.annotations.\"org.opencontainers.image.title\" == \"${task_version}.sh\")
+              | .annotations.\"org.opencontainers.image.title\"
+              "
           )
 
-          echo
-          echo "Attached migration file ${migration_file} to ${task_bundle}"
+          if [ -n "$filename" ]; then
+            if diff "$filename" "$migration_file" >/dev/null; then
+              found=true
+              break
+            else
+              echo "error: task bundle $task_bundle has migration artifact $artifact_ref, but the migration content is different: $filename" 1>&2
+              exit 1
+            fi
+          fi
+        done <<<"$artifact_refs"
 
-          return 0
+        # the same migration file exist
+        if [ "$found" == "true" ]; then
+          echo true
+        fi
+        # migratioan file doesn't exist
+        echo false
+      }
+
+      attach_migration_file() {
+        local -r task_bundle=$1
+        local -r task_version=$2
+        local -r migration_file=$3
+        local -r auth_json=$4
+
+        cd "${migration_file%/*}"
+        retry oras attach \
+          --registry-config "${auth_json}" \
+          --artifact-type "$ARTIFACT_TYPE_TEXT_XSHELLSCRIPT" \
+          --annotation "${ANNOTATION_IS_MIGRATION}=true" \
+          "$task_bundle" "${migration_file##*/}"
+
+        local status=$?
+        if [[ $status -ne 0 ]]; then
+          echo "failed to attach migration script file to $task_bundle"
+          echo 1
+        fi
+
+        echo "Attached migration file $migration_file to $task_bundle"
+
+        echo 0
       }
 
       # Find previous bundle that has a migration and output its digest.
       find_previous_migration_bundle_digest() {
-          local -r task_name=${1:?Missing task name}
-          local -r task_version=${2:?Missing task version}
-
-          local bundle_ref
-          bundle_ref=$(generate_tagged_task_bundle "$task_name" "$task_version")
-          local ns_repo=${bundle_ref%:*}  # remove tag
+          local ns_repo=${IMAGE%:*}  # remove tag
           ns_repo=${ns_repo#*/}  # remove registry
-          # Retain the tag used for matching tag names
-          local -r name_pattern="${bundle_ref##*:}-"
-          unset bundle_ref
 
-          local -r params="onlyActiveTags=true&filter_tag_name=like:${name_pattern}&limit=1"
+          # fetch 5 manifests to find out a task bundle since some of them are artifact
+          local -r params="onlyActiveTags=true&limit=5"
           local -r url_list_tags="https://quay.io/api/v1/repository/${ns_repo}/tag/?${params}"
 
-          local manifest_digest
-          manifest_digest=$(curl --fail -sL "$url_list_tags" | jq -r '.tags[].manifest_digest')
-          if [ -z "$manifest_digest" ]; then
+          local manifest_digests
+          manifest_digests=$(curl --fail -sL "$url_list_tags" | jq '.tags[] | select(.name | test("^((?!on-pr-).)*$"))' | jq -r '.manifest_digest')
+          if [ -z "$manifest_digests" ]; then
               # There is no tag yet. That would mean this is the first time to build the task bundle.
               return 0
           fi
-          curl --fail -sL -o /tmp/manifest.json "https://quay.io/v2/${ns_repo}/manifests/${manifest_digest}"
 
-          local has_migration
-          has_migration=$(jq -r ".annotations.\"${ANNOTATION_HAS_MIGRATION}\"" </tmp/manifest.json)
-          if [ "$has_migration" == "true" ]; then
+          # check migration file in gotten manifests in case artifact manifests are mixed with task bundle manifests
+          for manifest_digest in $manifest_digests
+          do
+            curl --fail -sL -o "${HOME}/manifest.json" "https://quay.io/v2/${ns_repo}/manifests/${manifest_digest}"
+            if ! jq -e '.annotations | has("'"$ANNOTATION_TASK_BUNDLE_DESCRIPTION"'")' "${HOME}/manifest.json" >/dev/null; then
+              # if annotation org.opencontainers.image.description doesn't exist, it means this is not task bundle, skip
+              continue
+            fi
+
+            local has_migration
+            has_migration=$(jq -r ".annotations.\"${ANNOTATION_HAS_MIGRATION}\"" <"${HOME}/manifest.json")
+            if [ "$has_migration" == "true" ]; then
               echo "$manifest_digest"
               return 0
-          fi
+            fi
 
-          local prev_bundle_digest
-          prev_bundle_digest=$(jq -r ".annotations.\"${ANNOTATION_PREVIOUS_MIGRATION_BUNDLE}\"" </tmp/manifest.json)
-          if [ -n "$prev_bundle_digest" ] && [ "$prev_bundle_digest" != "null" ]; then
+            local prev_bundle_digest
+            prev_bundle_digest=$(jq -r ".annotations.\"${ANNOTATION_PREVIOUS_MIGRATION_BUNDLE}\"" <"${HOME}/manifest.json")
+            if [ -n "$prev_bundle_digest" ] && [ "$prev_bundle_digest" != "null" ]; then
               # This bundle points to a previous bundle that has migration.
               echo "$prev_bundle_digest"
               return 0
-          fi
-
-          # Otherwise, output empty to indicate not point any bundle.
-          echo
+            fi
+            # Otherwise, output empty to indicate not point any bundle.
+            echo
+            return 0
+          done
           return 0
       }
 
@@ -315,14 +331,22 @@ spec:
       echo "info: finding the previous task bundle that has a migration" 1>&2
       previous_migration_bundle_digest=$(find_previous_migration_bundle_digest)
 
+      # check migration script in commit
+      has_migration=false
+      pushd "$(workspaces.source.path)/${SOURCE_CODE_DIR}"
       migration_file="${task_dir}/migrations/${task_version}.sh"
 
-      has_migration=false
-      if [ -f "$migration_file" ] && git show "$task_file_sha" --oneline --name-only | grep -q "$migration_file"; then
-          # There is a migration file matching the task concrete version and
-          # is included in the same commit with the task.
-          has_migration=true
+      if [ ! -d ".git" ]; then
+        echo ".git folder is not found, please switch to correct git root directory and check it again"
+        exit 1
       fi
+      if [ -f "$migration_file" ] && git show "$REVISION" --oneline --name-only | grep -q "$migration_file"; then
+        # There is a migration file matching the task concrete version and
+        # is included in the same commit with the task.
+        echo "there is an migration file ${migration_file} in revision ${REVISION}"
+        has_migration=true
+      fi
+      popd
 
       ANNOTATIONS=()
       ANNOTATIONS+=("org.opencontainers.image.source=${URL}")
@@ -375,7 +399,24 @@ spec:
       echo -n "${IMAGE_REF}" >"$(results.IMAGE_REF.path)"
 
       if [ "$has_migration" == "true" ]; then
-          attach_migration_file "$task_dir" "$concrete_task_version" "$task_bundle_with_digest" "$migration_file"
+        migration_file="$(workspaces.source.path)/${SOURCE_CODE_DIR}/${migration_file}"
+        has_migration_file=$(bundle_has_migration "${IMAGE_REF}" "${task_version}" "${migration_file}")
+        if [[ -z ${has_migration_file} ]]; then
+          echo "there is different migration script file in task bundle ${IMAGE_REF}, failed"
+          exit 1
+        fi
+
+        if [[ "${has_migration_file}" == "true" ]]; then
+          echo "the same migration file exists in task bundle ${IMAGE_REF}, skipped"
+          exit 0
+        fi
+
+        echo "attach migration script to $IMAGE_REF"
+        select-oci-auth "${IMAGE_REF}" > "${HOME}/auth.json"
+        if ! attach_migration_file "${IMAGE_REF}" "${task_version}" "${migration_file}" "${HOME}/auth.json"
+        then
+          exit 1
+        fi
       fi
 
       # cleanup task file
