feat(STONEINTG-1232): set indent to 2
Signed-off-by: Hongwei Liu <hongliu@redhat.com>

diff --git a/task/tkn-bundle/0.2/tkn-bundle.yaml b/task/tkn-bundle/0.2/tkn-bundle.yaml
--- a/task/tkn-bundle/0.2/tkn-bundle.yaml
+++ b/task/tkn-bundle/0.2/tkn-bundle.yaml
@@ -132,106 +132,106 @@ spec:
     - name: REVISION
       value: $(params.REVISION)
     script: |
-        #!/bin/env bash
+      #!/bin/env bash
 
-        set -o errexit
-        set -o pipefail
-        set -o nounset
+      set -o errexit
+      set -o pipefail
+      set -o nounset
 
-        mapfile -t FILES <"${TASK_FILE}"
-        [[ ${#FILES[@]} -eq 0 ]] &&
-          echo "No YAML files matched by \"$CONTEXT\" in \"/var/workdir/${SOURCE_CODE_DIR}\", aborting the build" &&
-          exit 1
-        exec 3>&1
+      mapfile -t FILES <"${TASK_FILE}"
+      [[ ${#FILES[@]} -eq 0 ]] &&
+        echo "No YAML files matched by \"$CONTEXT\" in \"/var/workdir/${SOURCE_CODE_DIR}\", aborting the build" &&
+        exit 1
+      exec 3>&1
 
-        function escape_tkn_bundle_arg() {
-          # the arguments to `tkn bundle --annotate` need to be escaped in a curious way
-          # see https://github.com/tektoncd/cli/issues/2402 for details
+      function escape_tkn_bundle_arg() {
+        # the arguments to `tkn bundle --annotate` need to be escaped in a curious way
+        # see https://github.com/tektoncd/cli/issues/2402 for details
 
-          local arg=$1
-          # replace single double-quotes with double double-quotes (this escapes the double-quotes)
-          local escaped_arg=${arg//\"/\"\"}
-          # wrap the whole thing in double-quotes (this escapes commas)
-          printf '"%s"' "$escaped_arg"
-        }
+        local arg=$1
+        # replace single double-quotes with double double-quotes (this escapes the double-quotes)
+        local escaped_arg=${arg//\"/\"\"}
+        # wrap the whole thing in double-quotes (this escapes commas)
+        printf '"%s"' "$escaped_arg"
+      }
 
-        # Check if task is kustomized
-        # A task considered to be kustomized when a kustomization file is found in the task dir
-        is_kustomized_task() {
-            local -r task_dir=$1
-            if [[ -f "$task_dir/kustomization.yaml" || -f "$task_dir/kustomization.yml" ]] ; then
-                return 0
-            fi
-            return 1
-        }
-
-        # Generate a task from the kustomization file
-        generate_kustomized_task() {
-            local -r task_dir=$1
-            local -r prepared_task_file="$task_dir/generated-kustomized-task.yaml"
-            kubectl kustomize "$task_dir" >"$prepared_task_file"
-            echo "$prepared_task_file"
-        }
-
-        # task_dir is where all the tasks definitions reside
-        # all tasks definitions are in the same task_dir, so extracting it from the first element is enough
-        task_dir=$(echo "${FILES[0]}" | awk -F'/' '{NF--; print $0}' OFS='/')
-
-        # If task is kustomized, generate it and replace the FILES value with the value of the generated task
-        # All other files will be ignored.
-        if is_kustomized_task "$task_dir"; then
-            echo "Generating a kustomized task from $task_dir"
-            FILES=("$(generate_kustomized_task "$task_dir")")
-        else
-            echo "Task is not Kustomized - continue"
+      # Check if task is kustomized
+      # A task considered to be kustomized when a kustomization file is found in the task dir
+      is_kustomized_task() {
+        local -r task_dir=$1
+        if [[ -f "$task_dir/kustomization.yaml" || -f "$task_dir/kustomization.yml" ]] ; then
+          return 0
         fi
+        return 1
+      }
 
-        ANNOTATIONS=()
-        ANNOTATIONS+=("org.opencontainers.image.source=${URL}")
-        ANNOTATIONS+=("org.opencontainers.image.revision=${REVISION}")
-        ANNOTATIONS+=("org.opencontainers.image.url=${URL}/tree/${REVISION}/${CONTEXT}")
+      # Generate a task from the kustomization file
+      generate_kustomized_task() {
+        local -r task_dir=$1
+        local -r prepared_task_file="$task_dir/generated-kustomized-task.yaml"
+        kubectl kustomize "$task_dir" >"$prepared_task_file"
+        echo "$prepared_task_file"
+      }
 
-        # Ensure an empty string is output rather than string "null" if the version label is not present
-        task_version=$(yq '.metadata.labels."app.kubernetes.io/version"' "${FILES[@]}" | sed '/null/d' | tr -d '[:space:]')
-        ANNOTATIONS+=("org.opencontainers.image.version=${task_version}")
+      # task_dir is where all the tasks definitions reside
+      # all tasks definitions are in the same task_dir, so extracting it from the first element is enough
+      task_dir=$(echo "${FILES[0]}" | awk -F'/' '{NF--; print $0}' OFS='/')
 
-        if [ -f "${task_dir}/README.md" ]; then
-          ANNOTATIONS+=("org.opencontainers.image.documentation=${URL}/tree/${REVISION}/${CONTEXT}/README.md")
-        fi
+      # If task is kustomized, generate it and replace the FILES value with the value of the generated task
+      # All other files will be ignored.
+      if is_kustomized_task "$task_dir"; then
+        echo "Generating a kustomized task from $task_dir"
+        FILES=("$(generate_kustomized_task "$task_dir")")
+      else
+        echo "Task is not Kustomized - continue"
+      fi
 
-        if [ -f "${task_dir}/TROUBLESHOOTING.md" ]; then
-          ANNOTATIONS+=("dev.tekton.docs.troubleshooting=${URL}/tree/${REVISION}/${CONTEXT}/TROUBLESHOOTING.md")
-        fi
+      ANNOTATIONS=()
+      ANNOTATIONS+=("org.opencontainers.image.source=${URL}")
+      ANNOTATIONS+=("org.opencontainers.image.revision=${REVISION}")
+      ANNOTATIONS+=("org.opencontainers.image.url=${URL}/tree/${REVISION}/${CONTEXT}")
 
-        if [ -f "${task_dir}/USAGE.md" ]; then
-          ANNOTATIONS+=("dev.tekton.docs.usage=${URL}/tree/${REVISION}/${CONTEXT}/USAGE.md")
-        fi
-        description=$(yq '.spec.description' "${FILES[@]}" | sed '/null/d' | tr -d '')
-        ANNOTATIONS+=("org.opencontainers.image.description=${description}")
+      # Ensure an empty string is output rather than string "null" if the version label is not present
+      task_version=$(yq '.metadata.labels."app.kubernetes.io/version"' "${FILES[@]}" | sed '/null/d' | tr -d '[:space:]')
+      ANNOTATIONS+=("org.opencontainers.image.version=${task_version}")
 
-        echo "Added annotations:"
-        ANNOTATION_FLAGS=()
-        for annotation in "${ANNOTATIONS[@]}"; do
-          ANNOTATION_FLAGS+=("--annotate" "$(escape_tkn_bundle_arg "$annotation")")
-          echo "    - $annotation"
-        done
+      if [ -f "${task_dir}/README.md" ]; then
+        ANNOTATIONS+=("org.opencontainers.image.documentation=${URL}/tree/${REVISION}/${CONTEXT}/README.md")
+      fi
 
-        echo "Pushing bundle ${IMAGE} to registry"
-        # shellcheck disable=SC2046
-        if ! OUT="$(retry tkn bundle push "${ANNOTATION_FLAGS[@]}" "$IMAGE" \
-          $(printf ' -f %s' "${FILES[@]}") |
-          tee /proc/self/fd/3)"
-        then
-          echo "Failed to push bundle ${IMAGE} to registry"
-          exit 1
-        fi
-        echo -n "$IMAGE" >"$(results.IMAGE_URL.path)"
-        digest="${OUT#*Pushed Tekton Bundle to *@}"
-        echo -n "${digest}" >"$(results.IMAGE_DIGEST.path)"
-        echo -n "${IMAGE}@${digest}" >"$(results.IMAGE_REF.path)"
+      if [ -f "${task_dir}/TROUBLESHOOTING.md" ]; then
+        ANNOTATIONS+=("dev.tekton.docs.troubleshooting=${URL}/tree/${REVISION}/${CONTEXT}/TROUBLESHOOTING.md")
+      fi
 
-        # cleanup task file
-        [[ -f "${TASK_FILE}" ]] && rm -f "${TASK_FILE}"
+      if [ -f "${task_dir}/USAGE.md" ]; then
+        ANNOTATIONS+=("dev.tekton.docs.usage=${URL}/tree/${REVISION}/${CONTEXT}/USAGE.md")
+      fi
+      description=$(yq '.spec.description' "${FILES[@]}" | sed '/null/d' | tr -d '')
+      ANNOTATIONS+=("org.opencontainers.image.description=${description}")
+
+      echo "Added annotations:"
+      ANNOTATION_FLAGS=()
+      for annotation in "${ANNOTATIONS[@]}"; do
+        ANNOTATION_FLAGS+=("--annotate" "$(escape_tkn_bundle_arg "$annotation")")
+        echo "    - $annotation"
+      done
+
+      echo "Pushing bundle ${IMAGE} to registry"
+      # shellcheck disable=SC2046
+      if ! OUT="$(retry tkn bundle push "${ANNOTATION_FLAGS[@]}" "$IMAGE" \
+        $(printf ' -f %s' "${FILES[@]}") |
+        tee /proc/self/fd/3)"
+      then
+        echo "Failed to push bundle ${IMAGE} to registry"
+        exit 1
+      fi
+      echo -n "$IMAGE" >"$(results.IMAGE_URL.path)"
+      digest="${OUT#*Pushed Tekton Bundle to *@}"
+      echo -n "${digest}" >"$(results.IMAGE_DIGEST.path)"
+      echo -n "${IMAGE}@${digest}" >"$(results.IMAGE_REF.path)"
+
+      # cleanup task file
+      [[ -f "${TASK_FILE}" ]] && rm -f "${TASK_FILE}"
     securityContext:
       runAsUser: 0
     workingDir: $(workspaces.source.path)
