feat(STONEINTG-1232): a few syntax fixes
Signed-off-by: Hongwei Liu <hongliu@redhat.com>

diff --git a/task/tkn-bundle/0.2/tkn-bundle.yaml b/task/tkn-bundle/0.2/tkn-bundle.yaml
--- a/task/tkn-bundle/0.2/tkn-bundle.yaml
+++ b/task/tkn-bundle/0.2/tkn-bundle.yaml
@@ -144,7 +144,6 @@ spec:
       # The annotation value points to the task bundle which has a migration that's most recent to the task with the annotation
       declare -r ANNOTATION_PREVIOUS_MIGRATION_BUNDLE="dev.konflux-ci.task.previous-migration-bundle"
 
-      # shellcheck disable=SC2153
       mapfile -t FILES <"${TASK_FILE}"
       [[ ${#FILES[@]} -eq 0 ]] &&
         echo "No YAML files matched by \"$CONTEXT\" in \"/var/workdir/${SOURCE_CODE_DIR}\", aborting the build" &&
@@ -248,23 +247,23 @@ spec:
         local -r task_version=$2
         local -r migration_file=$3
         local -r auth_json=$4
-
-        cd "${migration_file%/*}"
-        retry oras attach \
-          --registry-config "${auth_json}" \
-          --artifact-type "$ARTIFACT_TYPE_TEXT_XSHELLSCRIPT" \
-          --annotation "${ANNOTATION_IS_MIGRATION}=true" \
-          "$task_bundle" "${migration_file##*/}"
-
+        (
+          cd "${migration_file%/*}"
+          retry oras attach \
+            --registry-config "${auth_json}" \
+            --artifact-type "$ARTIFACT_TYPE_TEXT_XSHELLSCRIPT" \
+            --annotation "${ANNOTATION_IS_MIGRATION}=true" \
+            "$task_bundle" "${migration_file##*/}"
+        )
         local status=$?
         if [[ $status -ne 0 ]]; then
           echo "failed to attach migration script file to $task_bundle"
-          echo 1
+          return 1
         fi
 
         echo "Attached migration file $migration_file to $task_bundle"
 
-        echo 0
+        return 0
       }
 
       # Find previous bundle that has a migration and output its digest.
@@ -273,48 +272,55 @@ spec:
         ns_repo=${ns_repo#*/}  # remove registry
 
         # fetch manifests to find out a task bundle since some of them are artifact
-        local -r params="onlyActiveTags=true"
-        local -r url_list_tags="https://quay.io/api/v1/repository/${ns_repo}/tag/?${params}"
+        local page=1
+        while true; do
+          local -r params="onlyActiveTags=true&limit=50&page=$page"
+          local -r url_list_tags="https://quay.io/api/v1/repository/${ns_repo}/tag/?${params}"
 
-        local manifest_digests
-        manifest_digests=$(curl --fail -sL "$url_list_tags" | jq '.tags[] | select(.name | test("^(?!.*(on-pr-|sha)).*$"))' | jq -r '.manifest_digest')
-        if [ -z "$manifest_digests" ]; then
-            # There is no tag yet. That would mean this is the first time to build the task bundle.
-            return 0
-        fi
-
-        # check migration file in gotten manifests in case artifact manifests are mixed with task bundle manifests
-        for manifest_digest in $manifest_digests
-        do
-          curl --fail -sL -o "${HOME}/manifest.json" "https://quay.io/v2/${ns_repo}/manifests/${manifest_digest}"
-          if ! jq '(.mediaType == "application/vnd.docker.distribution.manifest.v2+json") and (.layers[0].annotations["dev.tekton.image.kind"] == "task")' "${HOME}/manifest.json" >/dev/null; then
-            # if mediaType is not "application/vnd.docker.distribution.manifest.v2+json" or image kind is not "task", it means this is not task bundle, skip
-            continue
+          local manifest_digests
+          # find out the task bundle manifest digests of the tags from push event containing neither "on-pr-" nor "sha"
+          manifest_digests=$(curl --fail -sL "$url_list_tags" | jq '.tags[] | select(.name | test("^(?!.*(on-pr-|sha)).*$"))' | jq -r '.manifest_digest')
+          if [ -z "$manifest_digests" ]; then
+              # There is no tag yet. That would mean this is the first time to build the task bundle.
+              return 0
           fi
 
-          local has_migration
-          has_migration=$(jq -r ".annotations.\"${ANNOTATION_HAS_MIGRATION}\"" <"${HOME}/manifest.json")
-          if [ "$has_migration" == "true" ]; then
-            echo "$manifest_digest"
-            return 0
-          fi
+          # check migration file in gotten manifests in case artifact manifests are mixed with task bundle manifests
+          for manifest_digest in $manifest_digests
+          do
+            curl --fail -sL -o "${HOME}/manifest.json" "https://quay.io/v2/${ns_repo}/manifests/${manifest_digest}"
+            if ! jq -e '(.mediaType == "application/vnd.docker.distribution.manifest.v2+json") and (.layers[0].annotations["dev.tekton.image.kind"] == "task")' "${HOME}/manifest.json" >/dev/null; then
+              # if mediaType is not "application/vnd.docker.distribution.manifest.v2+json" or image kind is not "task", it means this is not task bundle, skip
+              continue
+            fi
 
-          local prev_bundle_digest
-          prev_bundle_digest=$(jq -r ".annotations.\"${ANNOTATION_PREVIOUS_MIGRATION_BUNDLE}\"" <"${HOME}/manifest.json")
-          if [ -n "$prev_bundle_digest" ] && [ "$prev_bundle_digest" != "null" ]; then
-            # This bundle points to a previous bundle that has migration.
-            echo "$prev_bundle_digest"
+            local has_migration
+            has_migration=$(jq -r ".annotations.\"${ANNOTATION_HAS_MIGRATION}\"" <"${HOME}/manifest.json")
+            if [ "$has_migration" == "true" ]; then
+              echo "$manifest_digest"
+              return 0
+            fi
+
+            local prev_bundle_digest
+            prev_bundle_digest=$(jq -r ".annotations.\"${ANNOTATION_PREVIOUS_MIGRATION_BUNDLE}\"" <"${HOME}/manifest.json")
+            if [ -n "$prev_bundle_digest" ] && [ "$prev_bundle_digest" != "null" ]; then
+              # This bundle points to a previous bundle that has migration.
+              echo "$prev_bundle_digest"
+              return 0
+            fi
+            # Otherwise, output empty to indicate there is no previous bundle digest with migration file.
+            echo
             return 0
-          fi
-          # Otherwise, output empty to indicate not point any bundle.
-          echo
-          return 0
+          done
+          ((page++))
         done
+        # Otherwise, output empty to indicate not point any bundle.
+        echo
         return 0
       }
 
-      # task_dir is where all the tasks definitions reside
-      # all tasks definitions are in the same task_dir, so extracting it from the first element is enough
+      # task_dir is where the task definition reside
+      # this task run for only one task file, so extracting it from the first element is enough
       task_dir=$(echo "${FILES[0]}" | awk -F'/' '{NF--; print $0}' OFS='/')
       task_version=$(get_concrete_task_version "${FILES[0]}")
 
@@ -330,24 +336,23 @@ spec:
       echo "info: finding the previous task bundle that has a migration" 1>&2
       previous_migration_bundle_digest=$(find_previous_migration_bundle_digest)
 
-      # check if migration script file in commit if migration file doesn't exist in previous bundle digest
-      # since we allow only one migration script file for one task version
+      # check if migration script file in commit
       has_migration=false
-      migration_file="${task_dir}/migrations/${task_version}.sh"
-      if [[ -z ${previous_migration_bundle_digest} ]]; then
-        pushd "$(workspaces.source.path)/${SOURCE_CODE_DIR}"
-        if [ ! -d ".git" ]; then
-          echo ".git folder is not found, please switch to correct git root directory and check it again"
-          exit 1
-        fi
-        if [ -f "$migration_file" ] && git show "$REVISION" --oneline --name-only | grep -q "$migration_file"; then
-          # There is a migration file matching the task concrete version and
-          # is included in the same commit with the task.
-          echo "there is an migration file ${migration_file} in revision ${REVISION}"
-          has_migration=true
-        fi
-        popd
+      prefix="$(workspaces.source.path)/${SOURCE_CODE_DIR}/"
+      relative_task_dir="${task_dir#$prefix}" # get the task file path starting from "task"
+      migration_file="${relative_task_dir}/migrations/${task_version}.sh"
+      pushd "$(workspaces.source.path)/${SOURCE_CODE_DIR}"
+      if [ ! -d ".git" ]; then
+        echo ".git folder is not found, please switch to correct git root directory and check it again"
+        exit 1
       fi
+      if [ -f "$migration_file" ] && git show "$REVISION" --oneline --name-only | grep -q "$migration_file"; then
+        # There is a migration file matching the task concrete version and
+        # is included in the same commit with the task.
+        echo "there is an migration file ${migration_file} in revision ${REVISION}"
+        has_migration=true
+      fi
+      popd
 
       ANNOTATIONS=()
       ANNOTATIONS+=("org.opencontainers.image.source=${URL}")
@@ -421,7 +426,6 @@ spec:
       fi
 
       # cleanup task file
-      # shellcheck disable=SC2153
       [[ -f "${TASK_FILE}" ]] && rm -f "${TASK_FILE}"
     securityContext:
       runAsUser: 0
