fix(HACBS-1746): tasks must use image digests
To be sure that tasks are validating the expected image, we must use
digests. This commit adds new parameter to tasks IMAGE_DIGEST

Signed-off-by: Martin Basti <mbasti@redhat.com>

diff --git a/task/sbom-json-check/0.1/sbom-json-check.yaml b/task/sbom-json-check/0.1/sbom-json-check.yaml
--- a/task/sbom-json-check/0.1/sbom-json-check.yaml
+++ b/task/sbom-json-check/0.1/sbom-json-check.yaml
@@ -11,6 +11,9 @@ spec:
     - name: IMAGE_URL
       description: the fully qualified image name to be verified
       type: string
+    - name: IMAGE_DIGEST
+      description: image digest
+      type: string
   results:
     - description: Test output
       name: HACBS_TEST_OUTPUT
@@ -34,8 +37,10 @@ spec:
 
       mkdir /manifests/ && cd /manifests/
 
-      if ! oc image extract $(params.IMAGE_URL) --path '/root/buildinfo/content_manifests/*:/manifests/'; then
-        echo "Failed to extract manifests from image $(params.IMAGE_URL)"
+      image_with_digest="$(params.IMAGE_URL)@$(params.IMAGE_DIGEST)"
+
+      if ! oc image extract "${image_with_digest}" --path '/root/buildinfo/content_manifests/*:/manifests/'; then
+        echo "Failed to extract manifests from image ${image_with_digest}"
       fi
 
       touch fail_result.txt
