Mitigate quay.io instabilities by adding retries to commands using registry
STONEBLD-3488

Signed-off-by: Robert Cerven <rcerven@redhat.com>

diff --git a/task/buildah-remote/0.4/buildah-remote.yaml b/task/buildah-remote/0.4/buildah-remote.yaml
--- a/task/buildah-remote/0.4/buildah-remote.yaml
+++ b/task/buildah-remote/0.4/buildah-remote.yaml
@@ -315,6 +315,7 @@ spec:
         rsync -ra /additional-secret/ "$SSH_HOST:$BUILD_DIR/volumes/additional-secret/"
         rsync -ra /mnt/trusted-ca/ "$SSH_HOST:$BUILD_DIR/volumes/trusted-ca/"
         rsync -ra "$HOME/.docker/" "$SSH_HOST:$BUILD_DIR/.docker/"
+        rsync -ra "/usr/bin/retry" "$SSH_HOST:$BUILD_DIR/usr/bin/retry"
         rsync -ra "/tekton/results/" "$SSH_HOST:$BUILD_DIR/results/"
       fi
       if [ "${IMAGE_APPEND_PLATFORM}" == "true" ]; then
@@ -449,9 +450,14 @@ spec:
       if [ "${HERMETIC}" == "true" ]; then
         BUILDAH_ARGS+=("--pull=never")
         UNSHARE_ARGS+=("--net")
+        buildah_retries=3
 
         for image in $BASE_IMAGES; do
-          unshare -Ufp --keep-caps -r --map-users 1,1,65536 --map-groups 1,1,65536 --mount -- buildah pull "$image"
+          if ! /usr/bin/retry unshare -Ufp --keep-caps -r --map-users 1,1,65536 --map-groups 1,1,65536 --mount -- buildah pull --retry "$buildah_retries" "$image"
+          then
+            echo "Failed to pull base image ${image}"
+            exit 1
+          fi
         done
         echo "Build will be executed with network isolation"
       fi
@@ -718,6 +724,7 @@ spec:
           -v "${BUILD_DIR@Q}/volumes/additional-secret:/additional-secret:Z" \
           -v "${BUILD_DIR@Q}/volumes/trusted-ca:/mnt/trusted-ca:Z" \
           -v "${BUILD_DIR@Q}/.docker/:/root/.docker:Z" \
+          -v "${BUILD_DIR@Q}/usr/bin/retry:/usr/bin/retry:Z" \
           -v "${BUILD_DIR@Q}/results/:/tekton/results:Z" \
           -v "${BUILD_DIR@Q}/scripts:/scripts:Z" \
           "${PRIVILEGED_NESTED_FLAGS[@]@Q}" \
@@ -792,17 +799,18 @@ spec:
 
       echo "[$(date --utc -Ins)] Push image with unique tag"
 
-      retries=5
+      buildah_retries=3
+
       # Push to a unique tag based on the TaskRun name to avoid race conditions
       echo "Pushing to ${IMAGE%:*}:${TASKRUN_NAME}"
-      if ! buildah push \
+      if ! /usr/bin/retry buildah push \
         --format="$push_format" \
-        --retry "$retries" \
+        --retry "$buildah_retries" \
         --tls-verify="$TLSVERIFY" \
         "$IMAGE" \
-        "docker://${IMAGE%:*}:$(context.taskRun.name)";
+        "docker://${IMAGE%:*}:$(context.taskRun.name)"
       then
-        echo "Failed to push sbom image to ${IMAGE%:*}:$(context.taskRun.name) after ${retries} tries"
+        echo "Failed to push sbom image to ${IMAGE%:*}:$(context.taskRun.name)"
         exit 1
       fi
 
@@ -810,14 +818,14 @@ spec:
 
       # Push to a tag based on the git revision
       echo "Pushing to ${IMAGE}"
-      if ! buildah push \
+      if ! /usr/bin/retry buildah push \
         --format="$push_format" \
-        --retry "$retries" \
+        --retry "$buildah_retries" \
         --tls-verify="$TLSVERIFY" \
         --digestfile "$(workspaces.source.path)/image-digest" "$IMAGE" \
-        "docker://$IMAGE";
+        "docker://$IMAGE"
       then
-        echo "Failed to push sbom image to $IMAGE after ${retries} tries"
+        echo "Failed to push sbom image to $IMAGE"
         exit 1
       fi
 
@@ -1004,7 +1012,14 @@ spec:
 
       # Pre-select the correct credentials to work around cosign not supporting the containers-auth.json spec
       mkdir -p /tmp/auth && select-oci-auth "$(cat "$(results.IMAGE_REF.path)")" > /tmp/auth/config.json
-      DOCKER_CONFIG=/tmp/auth cosign attach sbom --sbom sbom.json --type "$SBOM_TYPE" "$(cat "$(results.IMAGE_REF.path)")"
+      # shellcheck disable=SC2034  # Variable is used by cosign indirectly
+      DOCKER_CONFIG=/tmp/auth
+      echo "Pushing sbom to registry"
+      if ! /usr/bin/retry cosign attach sbom --sbom sbom.json --type "$SBOM_TYPE" "$(cat "$(results.IMAGE_REF.path)")"
+      then
+          echo "Failed to push sbom to registry"
+          exit 1
+      fi
 
       # Remove tag from IMAGE while allowing registry to contain a port number.
       sbom_repo="${IMAGE%:*}"
diff --git a/task/clair-scan/0.2/clair-scan.yaml b/task/clair-scan/0.2/clair-scan.yaml
--- a/task/clair-scan/0.2/clair-scan.yaml
+++ b/task/clair-scan/0.2/clair-scan.yaml
@@ -118,8 +118,8 @@ spec:
         # we require in the policy rules, so we resort to running clair-action
         # twice to produce both quay and clair formatted output
         clair_report() {
-          { retry clair-action report --image-ref="$1" --db-path=/tmp/matcher.db --format=quay | tee "clair-result-$2.json"; } && \
-          { retry clair-action report --image-ref="$1" --db-path=/tmp/matcher.db --format=clair > "clair-report-$2.json"; }
+          { /usr/bin/retry clair-action report --image-ref="$1" --db-path=/tmp/matcher.db --format=quay | tee "clair-result-$2.json"; } && \
+          { /usr/bin/retry clair-action report --image-ref="$1" --db-path=/tmp/matcher.db --format=clair > "clair-report-$2.json"; }
         }
 
         for sha_file in image-manifest-*.sha; do
@@ -180,7 +180,12 @@ spec:
           digest=$(cat "image-manifest-$(arch "$f").sha")
           image_ref="${repository}@${digest}"
           echo "Attaching $f to ${image_ref}"
-          report_digest="$(retry oras attach --no-tty --format go-template='{{.digest}}' --registry-config "$HOME/auth.json" --artifact-type "${MEDIA_TYPE}" "${image_ref}" "$f:${MEDIA_TYPE}")"
+          if ! report_digest="$(/usr/bin/retry oras attach --no-tty --format go-template='{{.digest}}' --registry-config \
+            "$HOME/auth.json" --artifact-type "${MEDIA_TYPE}" "${image_ref}" "$f:${MEDIA_TYPE}")"
+          then
+            echo "Failed to attach ${f} to ${image_ref}"
+            exit 1
+          fi
           # shellcheck disable=SC2016
           reports_json="$(yq --output-format json --indent=0 eval-all '. as $i ireduce ({}; . * $i)' <(echo "${reports_json}") <(echo "${digest}: ${report_digest}"))"
         done
diff --git a/task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml b/task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml
--- a/task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml
+++ b/task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml
@@ -602,9 +602,13 @@ spec:
         if [ "${HERMETIC}" == "true" ]; then
           BUILDAH_ARGS+=("--pull=never")
           UNSHARE_ARGS+=("--net")
+          buildah_retries=3
 
           for image in $BASE_IMAGES; do
-            unshare -Ufp --keep-caps -r --map-users 1,1,65536 --map-groups 1,1,65536 --mount -- buildah pull "$image"
+            if ! /usr/bin/retry unshare -Ufp --keep-caps -r --map-users 1,1,65536 --map-groups 1,1,65536 --mount -- buildah pull --retry "$buildah_retries" "$image"; then
+              echo "Failed to pull base image ${image}"
+              exit 1
+            fi
           done
           echo "Build will be executed with network isolation"
         fi
@@ -985,11 +989,18 @@ spec:
         )
 
         echo "Attaching scan results to ${IMAGE_URL}"
-        upload_file "coverity-results.sarif" "application/sarif+json"
+        if ! /usr/bin/retry upload_file "coverity-results.sarif" "application/sarif+json"; then
+          echo "Failed to attach scan results to ${IMAGE_URL}"
+          exit 1
+        fi
 
         # upload excluded-findings.json if enabled
         if [ -f "excluded-findings.json" ]; then
-          upload_file "excluded-findings.json" "application/json"
+          echo "Attaching excluded findings to ${IMAGE_URL}"
+          if ! /usr/bin/retry upload_file "excluded-findings.json" "application/json"; then
+            echo "Failed to attach excluded findings to ${IMAGE_URL}"
+            exit 1
+          fi
         fi
       computeResources:
         limits:
diff --git a/task/sast-snyk-check/0.2/sast-snyk-check.yaml b/task/sast-snyk-check/0.2/sast-snyk-check.yaml
--- a/task/sast-snyk-check/0.2/sast-snyk-check.yaml
+++ b/task/sast-snyk-check/0.2/sast-snyk-check.yaml
@@ -135,6 +135,9 @@ spec:
         echo "Selecting auth"
         select-oci-auth $IMAGE_URL > $HOME/auth.json
         echo "Attaching to ${IMAGE_URL}"
-        retry oras attach --no-tty --registry-config "$HOME/auth.json" --artifact-type "${MEDIA_TYPE}" "${IMAGE_URL}" "${UPLOAD_FILE}:${MEDIA_TYPE}"
+        if ! /usr/bin/retry oras attach --no-tty --registry-config "$HOME/auth.json" --artifact-type "${MEDIA_TYPE}" "${IMAGE_URL}" "${UPLOAD_FILE}:${MEDIA_TYPE}"
+        then
+          echo "Failed to attach to ${IMAGE_URL}"
+        fi
   workspaces:
   - name: workspace
