buildah*/0.10: minor logging cleanup
- Move the "Update CA trust" message to the section where we know we
  will in fact be doing that.
- Add a "Run the build" log message to terminate the "Prepare the
  system" section. Also drop the "Run build command" message, since it's
  redundant now.
- Move the "Prepare Dockerfile" code to the "Run the build" section. The
  code doesn't do any preparation of Dockerfiles, it just finds the
  Dockerfile in the repo.
  - Note that konflux-build-cli can find the dockerfile on its own,
    so this wouldn't have to be done in Bash if not for the RHSM code
    that greps for 'subscription-manager register'. That code only
    exists in Bash and does need the dockerfile path.

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

diff --git a/task/buildah-oci-ta/0.10/buildah-oci-ta.yaml b/task/buildah-oci-ta/0.10/buildah-oci-ta.yaml
--- a/task/buildah-oci-ta/0.10/buildah-oci-ta.yaml
+++ b/task/buildah-oci-ta/0.10/buildah-oci-ta.yaml
@@ -451,8 +451,6 @@ spec:
         #!/bin/bash
         set -euo pipefail
 
-        echo "[$(date --utc -Ins)] Update CA trust"
-
         ca_bundle=/mnt/trusted-ca/ca-bundle.crt
         proxy_ca_bundle=/mnt/proxy-ca-bundle/ca-bundle.crt
         update_ca_trust=false
@@ -470,18 +468,8 @@ spec:
         fi
 
         if [ "$update_ca_trust" = "true" ]; then
+          echo "[$(date --utc -Ins)] Update CA trust"
           update-ca-trust
-        fi
-
-        echo "[$(date --utc -Ins)] Prepare Dockerfile"
-
-        if [ -e "$SOURCE_CODE_DIR/$CONTEXT/$DOCKERFILE" ]; then
-          dockerfile_path="$(pwd)/$SOURCE_CODE_DIR/$CONTEXT/$DOCKERFILE"
-        elif [ -e "$SOURCE_CODE_DIR/$DOCKERFILE" ]; then
-          dockerfile_path="$(pwd)/$SOURCE_CODE_DIR/$DOCKERFILE"
-        else
-          echo "Cannot find Dockerfile $DOCKERFILE"
-          exit 1
         fi
 
         echo "[$(date --utc -Ins)] Prepare system (architecture: $(uname -m))"
@@ -513,6 +501,17 @@ spec:
         cp "$kbc_mount"/usr/local/bin/konflux-build-cli /usr/local/bin/
         buildah umount "$kbc_container"
         buildah rm "$kbc_container"
+
+        echo "[$(date --utc -Ins)] Run the build"
+
+        if [ -e "$SOURCE_CODE_DIR/$CONTEXT/$DOCKERFILE" ]; then
+          dockerfile_path="$(pwd)/$SOURCE_CODE_DIR/$CONTEXT/$DOCKERFILE"
+        elif [ -e "$SOURCE_CODE_DIR/$DOCKERFILE" ]; then
+          dockerfile_path="$(pwd)/$SOURCE_CODE_DIR/$DOCKERFILE"
+        else
+          echo "Cannot find Dockerfile $DOCKERFILE"
+          exit 1
+        fi
 
         if [ -n "${ANNOTATIONS_FILE}" ] && [ -f "${SOURCE_CODE_DIR}/${ANNOTATIONS_FILE}" ]; then
           ANNOTATIONS_FILE=$(realpath "${SOURCE_CODE_DIR}/${ANNOTATIONS_FILE}")
@@ -621,7 +620,6 @@ spec:
           "$@" # --annotations, --labels, --envs, --build-args
         )
 
-        echo "[$(date --utc -Ins)] Run build command"
         echo "[$(date --utc -Ins)] $(printf '%q ' "${cmd[@]}")"
 
         "${cmd[@]}"
