feat[HACBS-1271]: Store output from ClamAV into result
Signed-off-by: Sri Vignesh <sselvan@redhat.com>

diff --git a/task/clamav-scan/0.1/clamav-scan.yaml b/task/clamav-scan/0.1/clamav-scan.yaml
--- a/task/clamav-scan/0.1/clamav-scan.yaml
+++ b/task/clamav-scan/0.1/clamav-scan.yaml
@@ -8,6 +8,9 @@ metadata:
     tekton.dev/tags: "virus, appstudio, hacbs"
   name: clamav-scan
 spec:
+  results:
+    - name: HACBS_TEST_OUTPUT
+      description: test output
   params:
     - name: image-digest
       description: Image digest to scan
@@ -107,6 +110,22 @@ spec:
 
         if __name__ == "__main__":
             main()
+    - name: store-hacbs-test-output-result
+      image: quay.io/redhat-appstudio/hacbs-test:latest
+      script: |
+        HACBS_ERROR_OUTPUT=$(jq -rc --arg date $(date +%s) --null-input \
+          '{result: "ERROR", timestamp: $date}')
+        if [ -f /tekton/home/clamscan-result.json ];
+        then
+          cat /tekton/home/clamscan-result.json
+          HACBS_TEST_OUTPUT=$(jq -rce --arg date $(date +%s) \
+            '. | { result: (if (.infected_files != "0") then "FAILURE" else "SUCCESS" end),
+                    timestamp: $date,
+                    successes: 1,
+                    failures: .infected_files
+                  }' /tekton/home/clamscan-result.json || true)
+        fi
+        echo "${HACBS_TEST_OUTPUT:-${HACBS_ERROR_OUTPUT}}" | tee $(results.HACBS_TEST_OUTPUT.path)
   # sidecar is rebuilt daily(is meant to be updated daily), hence the usage of the tag instead of digest
   # provides latest virus database for clamscan only
   # does not execute anything
