STONEBLD-1936 : Retry show sbom task and don't fail on error

diff --git a/task/show-sbom/0.1/show-sbom.yaml b/task/show-sbom/0.1/show-sbom.yaml
--- a/task/show-sbom/0.1/show-sbom.yaml
+++ b/task/show-sbom/0.1/show-sbom.yaml
@@ -25,11 +25,20 @@ spec:
     - name: IMAGE_URL
       value: $(params.IMAGE_URL)
     script: |
-       #!/busybox/sh
-       cosign download sbom $IMAGE_URL 2>err
-       RET=$?
-       if [ $RET -ne 0 ]; then
-         echo Failed to get SBOM >&2
-         cat err >&2
-       fi
-       exit $RET
+      #!/busybox/sh
+      status=-1
+      max_try=5
+      wait_sec=2
+      for run in $(seq 1 $max_try); do
+        status=0
+        cosign download sbom $IMAGE_URL 2>>err
+        status=$?
+        if [ "$status" -eq 0 ]; then
+          break
+        fi
+        sleep $wait_sec
+      done
+      if [ "$status" -ne 0 ]; then
+          echo "Failed to get SBOM after ${max_try} tries" >&2
+          cat err >&2
+      fi
