Use buildah --retry parameter
Signed-off-by: cmoulliard <cmoulliard@redhat.com>

diff --git a/task/build-paketo-builder/0.1/build-paketo-builder.yaml b/task/build-paketo-builder/0.1/build-paketo-builder.yaml
--- a/task/build-paketo-builder/0.1/build-paketo-builder.yaml
+++ b/task/build-paketo-builder/0.1/build-paketo-builder.yaml
@@ -397,19 +397,6 @@ spec:
             export IMAGE
           fi
           
-          retry() {
-            status=-1
-            max_run=5
-            sleep_sec=10
-          
-            for run in $(seq 1 $max_run); do
-              status=0
-              [ "$run" -gt 1 ] && sleep $sleep_sec
-              "$@" && break || status=$?
-            done
-            return $status
-          }
-          
           ca_bundle=/mnt/trusted-ca/ca-bundle.crt
           if [ -f "$ca_bundle" ]; then
             echo "INFO: Using mounted CA bundle: $ca_bundle"
@@ -440,26 +427,31 @@ spec:
           fi
           
           buildah --storage-driver $STORAGE_DRIVER commit "${BUILDAH_ARGS[@]}" $container $IMAGE
-          set +x
+
           echo "##########################################################################################"
           echo "Pushing to ${IMAGE%:*}:${TASKRUN_NAME}"
           echo "##########################################################################################"
-          if ! retry buildah --storage-driver $STORAGE_DRIVER push \
+          retries=5
+          if ! buildah push \
+            --retry "$retries" \
+            --storage-driver $STORAGE_DRIVER \
             --tls-verify="$TLSVERIFY" \
             "$IMAGE" \
             "docker://${IMAGE%:*}:$(context.taskRun.name)"; then
-            echo "Failed to push sbom image to ${IMAGE%:*}:$(context.taskRun.name) after ${max_run} tries"
+            echo "Failed to push sbom image to ${IMAGE%:*}:$(context.taskRun.name) after ${retries} tries"
             exit 1
           fi
           
           echo "##########################################################################################"
           echo "Pushing to ${IMAGE}"
           echo "##########################################################################################"
-          if ! retry buildah --storage-driver $STORAGE_DRIVER push \
+          if ! buildah push \
+            --retry "$retries" \
+            --storage-driver $STORAGE_DRIVER \
             --tls-verify="$TLSVERIFY" \
             --digestfile "/var/workdir/image-digest" "$IMAGE" \
             "docker://$IMAGE"; then
-            echo "Failed to push sbom image to $IMAGE after ${max_run} tries"
+            echo "Failed to push sbom image to $IMAGE after ${retries} tries"
             exit 1
           fi
           
