push to a unique tag in buildah tasks
- Built image in buildah task is pushed to
a location specified in the `IMAGE` param
- This location does not have to be unique
when running multiple PipelineRuns on the
same revision
- A race condition can occur resulting
in a failure
- Besides pushing to `IMAGE`, push to a
tag named after the TaskRun name which
should be unique

diff --git a/task/buildah-oci-ta/0.2/buildah-oci-ta.yaml b/task/buildah-oci-ta/0.2/buildah-oci-ta.yaml
--- a/task/buildah-oci-ta/0.2/buildah-oci-ta.yaml
+++ b/task/buildah-oci-ta/0.2/buildah-oci-ta.yaml
@@ -662,6 +662,15 @@ spec:
 
         buildah commit "${BUILDAH_ARGS[@]}" $container $IMAGE
 
+        echo "Pushing to ${IMAGE%:*}:${TASKRUN_NAME}"
+        if ! retry buildah push \
+          --tls-verify="$TLSVERIFY" \
+          "$IMAGE" \
+          "docker://${IMAGE%:*}:$(context.taskRun.name)"; then
+          echo "Failed to push sbom image to ${IMAGE%:*}:$(context.taskRun.name) after ${max_run} tries"
+          exit 1
+        fi
+
         echo "Pushing to ${IMAGE}"
         if ! retry buildah push \
           --tls-verify="$TLSVERIFY" \
